name: allah_names
description: App with Allah names
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # // TODO: UX/UI
  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  flutter_animated_icons: ^1.0.1
  animated_icon_button: ^1.0.2
  dynamic_height_grid_view: ^0.0.3
  auto_size_text: ^3.0.0
  lottie: ^2.3.2
  # // TODO: State
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  # // TODO: InApp
  # // TODO: Services
  logger: ^1.3.0
  firebase_crashlytics: ^3.1.2
  talker_flutter: ^2.4.3
  device_preview: ^1.1.0
  talker: ^2.4.0
  talker_bloc_logger: ^1.1.0
  intl: ^0.17.0
  firebase_core: ^2.10.0
  firebase_analytics: ^10.2.1
  provider: ^6.0.5
  get_it: ^7.3.0
  pretty_dio_logger: ^1.3.1
  auto_route: ^6.4.0
  # // TODO: Preferences
  shared_preferences: ^2.1.0
  font_awesome_flutter: ^10.4.0
  equatable: ^2.0.5
  visible_opacity: ^2.0.0
  easy_debounce: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^6.2.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_launcher_icon.webp"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/json/

  fonts:
    - family: 'Gilroy KZ'
      fonts:
        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 100
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Extrabold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
    - family: 'scheherazaderegular'
      fonts:
        - asset: assets/fonts/Scheherazade-Regular.ttf
        - asset: assets/fonts/Scheherazade-Bold.ttf
          weight: 700
    - family: 'Merge'
      fonts:
        - asset: assets/fonts/Merge_Pro_Bold.otf
          weight: 700


    - family: Typicons
      fonts:
        - asset: assets/fonts/Typicons.ttf
    - family: Allah1
      fonts:
        - asset: assets/fonts/allah1.ttf
    - family: RoundedCorners
      fonts:
        - asset: assets/fonts/roundedCorners.ttf